# Generated by Django 4.0.2 on 2022-12-06 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('pfp', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('sport', models.CharField(choices=[('none', 'None'), ('football', 'Football'), ('hockey', 'Hockey'), ('cricket', 'Cricket'), ('basketball', 'Basketball'), ('rugby', 'Rugby'), ('volleyball', 'Volleyball'), ('videogames', 'Prefer Video Games'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('tabletennis', 'Table Tennis')], max_length=50, null=True)),
                ('hobbies', models.CharField(choices=[('none', 'None'), ('dancing', 'Dancing'), ('singing', 'Singing'), ('acting', 'Acting'), ('reading', 'Reading'), ('drawing', 'Drawing'), ('writing', 'Writing'), ('swimming', 'Swimming')], max_length=50, null=True)),
                ('age', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age_gte_18'),
        ),
    ]
