# Generated by Django 4.0.2 on 2022-12-06 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dm',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('dmtext', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fpfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dm')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
