# Generated by Django 4.0.2 on 2023-01-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(-1, 'Prefer not to disclose'), (0, 'Female'), (1, 'Male')], default=-1),
        ),
    ]
