# Generated by Django 4.0.2 on 2023-01-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.PositiveIntegerField(choices=[(80, 'None'), (81, 'Dancing'), (82, 'Singing'), (83, 'Acting'), (84, 'Reading'), (85, 'Drawing'), (86, 'Writing'), (87, 'Swimming')], default=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport',
            field=models.PositiveIntegerField(choices=[(50, 'None'), (51, 'Football'), (52, 'Hockey'), (53, 'Cricket'), (54, 'Basketball'), (55, 'Rugby'), (56, 'Volleyball'), (57, 'Prefer Video Games'), (58, 'Badminton'), (59, 'Tennis'), (599, 'Table Tennis')], default=50),
        ),
    ]
