# Generated by Django 4.0.2 on 2023-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_profile_hobbies_alter_profile_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictmatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport1', models.PositiveIntegerField(null=True)),
                ('sport2', models.PositiveIntegerField(null=True)),
                ('hobbies1', models.PositiveIntegerField(null=True)),
                ('hobbies2', models.PositiveIntegerField(null=True)),
                ('age1', models.PositiveIntegerField(null=True)),
                ('age2', models.PositiveIntegerField(null=True)),
                ('gender1', models.PositiveIntegerField(null=True)),
                ('gender2', models.PositiveIntegerField(null=True)),
                ('result', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
