# Generated by Django 4.0.2 on 2023-01-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_predictmatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Predictmatch',
        ),
    ]
