# Generated by Django 4.0.2 on 2023-01-29 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_delete_predictmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictmatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport1', models.PositiveIntegerField(null=True)),
                ('sport2', models.PositiveIntegerField(null=True)),
                ('hobbies1', models.PositiveIntegerField(null=True)),
                ('hobbies2', models.PositiveIntegerField(null=True)),
                ('age1', models.PositiveIntegerField(null=True)),
                ('age2', models.PositiveIntegerField(null=True)),
                ('gender1', models.PositiveIntegerField(null=True)),
                ('gender2', models.PositiveIntegerField(null=True)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentuser', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
