# Generated by Django 4.0.2 on 2023-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_predictmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmatch',
            name='gender1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='predictmatch',
            name='gender2',
            field=models.IntegerField(null=True),
        ),
    ]
