# Generated by Django 4.0.2 on 2023-02-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_piro'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piro',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(71, 'Classic'), (72, 'Booster'), (73, 'Premium')]),
        ),
    ]
