# Generated by Django 4.0.2 on 2023-02-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_profile_private_alter_piro_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
