# Generated by Django 4.0.2 on 2023-02-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_notofication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notofication',
        ),
    ]
