# Generated by Django 4.0.2 on 2023-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dm',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.PositiveIntegerField(choices=[(90, 'None'), (91, 'Follow'), (92, 'Message')], default=90),
        ),
    ]
