# Generated by Django 4.0.2 on 2023-02-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_dm_options_alter_notification_ntype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
    ]
