# Generated by Django 4.0.2 on 2023-02-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_netgraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Netgraph',
        ),
    ]
