# Generated by Django 4.0.2 on 2023-08-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_networkgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('inpimage', models.ImageField(upload_to='caption_images')),
                ('contentlength', models.PositiveIntegerField(choices=[(11, 'Long'), (12, 'Medium'), (13, 'Short')], default=11)),
            ],
        ),
    ]
