# Generated by Django 4.0.2 on 2023-10-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_hub_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubdm',
            name='fpfp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile'),
        ),
        migrations.AddField(
            model_name='hubdm',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hubdm'),
        ),
    ]
