# Generated by Django 4.0.2 on 2023-12-04 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0034_hubdm_fpfp_hubdm_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tohub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hub'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntouser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.PositiveIntegerField(choices=[(90, 'None'), (91, 'Follow'), (92, 'Message'), (93, 'Hub Message')], default=90),
        ),
    ]
