# Generated by Django 4.0.2 on 2024-02-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_meetings_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meetings',
        ),
    ]
