# Generated by Django 4.0.2 on 2024-02-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.meeting'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.PositiveIntegerField(choices=[(90, 'None'), (91, 'Follow'), (92, 'Message'), (93, 'Hub Message'), (94, 'Hub Member'), (95, 'Meeting')], default=90),
        ),
    ]
