# Generated by Django 4.0.2 on 2024-02-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_notification_meeting_alter_notification_ntype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['scheduled_date', 'scheduled_time']},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='is_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='in_meetings',
            field=models.BooleanField(default=False),
        ),
    ]
