# Generated by Django 4.0.2 on 2024-02-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_meeting_options_remove_meeting_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='in_meetings',
            new_name='in_meeting',
        ),
    ]
