# Generated by Django 4.0.2 on 2024-02-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_rename_in_meetings_profile_in_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='in_meeting',
            field=models.CharField(default='', max_length=100),
        ),
    ]
