# Generated by Django 4.0.2 on 2024-02-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_profile_in_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='recurring_type',
            field=models.PositiveIntegerField(choices=[(30, 'None'), (31, 'Daily'), (32, 'Weekly'), (33, 'Alternate')], default=30),
        ),
    ]
